GET http://localhost:3000/subscribers
    
###
GET http://localhost:3000/subscribers/5fb13365c7d8d31b3c6f2639
    
###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "amazing person",
    "subscribedToChannel": "web simplified"
}

###
DELETE http://localhost:3000/subscribers/5fb13365c7d8d31b3c6f2639

###
PATCH http://localhost:3000/subscribers/5fb13365c7d8d31b3c6f2639